version: '3.5'
services:

  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    platform: linux/amd64
    restart: unless-stopped
    command: -tou-accept -email ${HONEYGAIN_USERNAME} -pass ${HONEYGAIN_PASSWORD} -device ${HONEYGAIN_DEVICE}
    env_file:
      - config/honeygain.env

  earnapp:
    image: fazalfarhan01/earnapp:lite
    container_name: earnapp
    restart: unless-stopped
    env_file:
      - config/earnapp.env

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 4000
    ports:
      - 4000:3000
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:arm32v7-latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies

volumes:
  portainer_data:
