version: '3.5'
services:

  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    platform: linux/amd64
    restart: unless-stopped
    command: -tou-accept -email ${HONEYGAIN_USERNAME} -pass ${HONEYGAIN_PASSWORD} -device ${HONEYGAIN_DEVICE}
    env_file:
      - honeygain.env

  earnapp:
    image: fazalfarhan01/earnapp:lite
    container_name: earnapp
    restart: unless-stopped
    env_file:
      - earnapp.env

  packetstream:
    image: packetstream/packetstream-agent:latest
    container_name: packetstream
    restart: unless-stopped
    network_mode: host
    environment:
      - PS_USER=<your_username>
      - PS_PASSWORD=<your_password>
      - PS_CONTAINER_NAME=packetstream
      - PS_LOGS_PATH=/var/log/packetstream/
    env_file:
      - packetstream.env
    volumes:
      - ./packetstream:/var/log/packetstream/