version: '3.5'
services:

  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    platform: linux/amd64
    restart: unless-stopped
    command: -tou-accept -email ${HONEYGAIN_USERNAME} -pass ${HONEYGAIN_PASSWORD} -device ${HONEYGAIN_DEVICE}
    env_file:
      - config/honeygain.env

  earnapp:
    image: fazalfarhan01/earnapp:lite
    container_name: earnapp
    restart: unless-stopped
    env_file:
      - config/earnapp.env

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
