version: '3.5'
services:

  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    platform: linux/amd64
    restart: unless-stopped
    command: -tou-accept -email ${HONEYGAIN_USERNAME} -pass ${HONEYGAIN_PASSWORD} -device ${HONEYGAIN_DEVICE}
    env_file:
      - env/honeygain.env

  earnapp:
    image: fazalfarhan01/earnapp:lite
    container_name: earnapp
    restart: unless-stopped
    env_file:
      - env/earnapp.env

  xmrig:
    image: metal3d/xmrig:latest
    container_name: xmrig
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - env/xmrig.env
