version: '3.5'
services:

  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    platform: linux/amd64
    restart: unless-stopped
    command: -tou-accept -email ${HONEYGAIN_USERNAME} -pass ${HONEYGAIN_PASSWORD} -device ${HONEYGAIN_DEVICE}
    env_file:
      - config/honeygain.env

  earnapp:
    image: fazalfarhan01/earnapp:lite
    container_name: earnapp
    restart: unless-stopped
    env_file:
      - config/earnapp.env

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - "6000:3000"
    networks:
      - rpi_network
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Lisbon
      - PORT=5055
    ports:
      - "5055:5055"
    volumes:
      - ./config/overseer:/app/config

volumes:
  portainer_data:

networks:
  rpi_network:
    external: true
