version: '3.5'
services:

  redis:
    image: redis:latest
    container_name: paperless-redis
    restart: unless-stopped

  paperless:
    image: jonaswinkler/paperless-ng:latest
    container_name: paperless
    restart: unless-stopped
    ports:
      - 8000:8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    #env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://redis:6379
    depends_on:
      - redis


volumes:
  data:
  media: