---
- name: Define the list of apt dependencies
  set_fact:
    apt_dependencies:
      - python3
      - python3-pip
      - awscli
      - git
      - jq
      - ripgrep
      - htop
      - hstr
      - exa
      - bash-completion

- name: Install apt dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_dependencies }}"

- name: Configure hstr in bash
  command: "hstr --show-configuration >> {{ ansible_env.PWD }}/.bashrc"
  args:
    executable: bash

- name: Reload Bash configuration
  command: "source {{ ansible_env.PWD }}/.bashrc"
  args:
    executable: bash

- name: Define the list of pip dependencies
  set_fact:
    pip_dependencies:
      - boto
      - botocore

- name: Install pip dependencies
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pip_dependencies }}"
