---
- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Install Docker Community Edition
  apt:
    name: docker-ce
    state: present

- name: Install pip3 (Python package installer)
  apt:
    name: python3-pip
    state: present

- name: Add docker permissions to the user
  command: "sudo usermod -aG docker ${USER}"

# TODO: Find a way to fix this
#- name: Install Docker Compose with pip3
#  command: "/usr/bin/sudo /usr/bin/pip3 install -U docker-compose"
#  args:
#    executable: /bin/bash

#- name: Install Docker Compose with pip3 for a specific user
#  community.general.docker_compose:
#    executable: pip3
#    state: latest
#  vars:
#    user: tilt

#- name: Install Docker Compose with pip3 for a specific user
#  command: "/usr/bin/sudo -H -u tilt   /usr/bin/pip3 install --upgrade docker-compose"