---
- name: Install dependencies
  apt:
    name:
      - python3
      - awscli
      - git
      - jq
      - ripgrep
      - htop
      - hstr
      - exa
      - bash-completion
    state: present

- name: Install pip3 (Python package installer)
  apt:
    name: python3-pip
    state: present

- name: Install boto and botocore with pip
  pip:
    name:
      - boto
      - botocore
    state: latest
    executable: /usr/bin/pip3
