---
- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Install Docker Community Edition
  apt:
    name: docker-ce
    state: present

- name: Add docker permissions to the user
  command: "sudo usermod -aG docker ${USER}"