---
- name: Install dependencies for Raspberry Pi
  hosts: raspberrypi
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name:
          - htop
          - ripgrep
          - hstr
          - git
          - jq
          - exa
          - bash-completion
        state: present
