---
- name: Restart Docker Service EarnApp
  hosts: raspberrypi
  become: true
  gather_facts: true
  vars:
    project_dir: /home/tilt/raspberry-pi
  tasks:
    - name: Restart earnapp via compose
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        services:
          - earnapp
        state: restarted
